/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentCouncilRouteImport } from './routes/student-council'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AdminStudentCouncilRouteImport } from './routes/admin.student-council'
import { Route as AdminSiteContentRouteImport } from './routes/admin.site-content'
import { Route as AdminResearchRouteImport } from './routes/admin.research'
import { Route as AdminPlacementsRouteImport } from './routes/admin.placements'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFacultyRouteImport } from './routes/admin.faculty'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDownloadsRouteImport } from './routes/admin.downloads'
import { Route as AdminAchievementsRouteImport } from './routes/admin.achievements'

const StudentCouncilRoute = StudentCouncilRouteImport.update({
  id: '/student-council',
  path: '/student-council',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentCouncilRoute = AdminStudentCouncilRouteImport.update({
  id: '/student-council',
  path: '/student-council',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResearchRoute = AdminResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacementsRoute = AdminPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/notices': typeof NoticesRoute
  '/placements': typeof PlacementsRoute
  '/research': typeof ResearchRoute
  '/student-council': typeof StudentCouncilRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/student-council': typeof AdminStudentCouncilRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/notices': typeof NoticesRoute
  '/placements': typeof PlacementsRoute
  '/research': typeof ResearchRoute
  '/student-council': typeof StudentCouncilRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/student-council': typeof AdminStudentCouncilRoute
  '/events/$id': typeof EventsIdRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/notices': typeof NoticesRoute
  '/placements': typeof PlacementsRoute
  '/research': typeof ResearchRoute
  '/student-council': typeof StudentCouncilRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/admin/student-council': typeof AdminStudentCouncilRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/downloads'
    | '/faculty'
    | '/gallery'
    | '/news'
    | '/notices'
    | '/placements'
    | '/research'
    | '/student-council'
    | '/admin/achievements'
    | '/admin/downloads'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/notices'
    | '/admin/placements'
    | '/admin/research'
    | '/admin/site-content'
    | '/admin/student-council'
    | '/events/$id'
    | '/admin/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/contact'
    | '/downloads'
    | '/faculty'
    | '/gallery'
    | '/news'
    | '/notices'
    | '/placements'
    | '/research'
    | '/student-council'
    | '/admin/achievements'
    | '/admin/downloads'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/notices'
    | '/admin/placements'
    | '/admin/research'
    | '/admin/site-content'
    | '/admin/student-council'
    | '/events/$id'
    | '/admin'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/downloads'
    | '/faculty'
    | '/gallery'
    | '/news'
    | '/notices'
    | '/placements'
    | '/research'
    | '/student-council'
    | '/admin/achievements'
    | '/admin/downloads'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/gallery'
    | '/admin/news'
    | '/admin/notices'
    | '/admin/placements'
    | '/admin/research'
    | '/admin/site-content'
    | '/admin/student-council'
    | '/events/$id'
    | '/admin/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  NoticesRoute: typeof NoticesRoute
  PlacementsRoute: typeof PlacementsRoute
  ResearchRoute: typeof ResearchRoute
  StudentCouncilRoute: typeof StudentCouncilRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-council': {
      id: '/student-council'
      path: '/student-council'
      fullPath: '/student-council'
      preLoaderRoute: typeof StudentCouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/student-council': {
      id: '/admin/student-council'
      path: '/student-council'
      fullPath: '/admin/student-council'
      preLoaderRoute: typeof AdminStudentCouncilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-content': {
      id: '/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/research': {
      id: '/admin/research'
      path: '/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AdminResearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/placements': {
      id: '/admin/placements'
      path: '/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AdminPlacementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminPlacementsRoute: typeof AdminPlacementsRoute
  AdminResearchRoute: typeof AdminResearchRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminStudentCouncilRoute: typeof AdminStudentCouncilRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminPlacementsRoute: AdminPlacementsRoute,
  AdminResearchRoute: AdminResearchRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminStudentCouncilRoute: AdminStudentCouncilRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  NoticesRoute: NoticesRoute,
  PlacementsRoute: PlacementsRoute,
  ResearchRoute: ResearchRoute,
  StudentCouncilRoute: StudentCouncilRoute,
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
